### ISSUE TITLE
Use DokuWiki's own HTTP client

### ISSUE THREAD

**Issue by splitbrain** [RaD/dokuwiki-seqdia#2]
Instead of depending on a PEAR class, you should make use of DokuWiki's own HTTP library in in inc/HTTPClient.php

**Comment by RaD** [comment]
Fixed at commit d11da36144d99ea37a10464925ad54b67028354d.

**Comment by RaD** [comment]
It seems I need to rollback to HTTPRequest:
[Thu Nov 11 13:52:12 2010] [error] [client 10.77.6.12] request failed: URI too long (longer than 8190)

**Comment by RaD** [comment]
Patch from splitbrain.
